### ISSUE TITLE
question and issue regarding "structure"

### ISSUE THREAD

**Issue by Nikoleta-v3** [kullrich/orthomap#3]
1. One question that I have is that currently a user has to do 

```python
from orthomap import qlin
```

to use the function within `qlin`. It is not possible to do

```python
import orthomap

orthomap.qlin
```

Is this a functionality we want to implement? 

2. One issue that I have is that there is a file called `orthomap.py` and the name of the package is also  `orthomap`. This could become confusing. Should we rename the file?

**Comment by kullrich** [comment]
Yes, but one can use e.g.:
```
from orthomap import qlin
qlin.get_qlin()
```
The `qlin` function is just to be able to use sub-commands and is defining the "sub-module", this is why `orthomap.orthomap` is fine for me, since this is what the sub-command is supposed to do.

**Comment by kullrich** [comment]
Hi, regarding this:
```
    # lines 61 (onwards) and 66 (onwards) were the same, because if both arguments
    # are given we are still returning results based on the `taxid`.
```
That is true, anyhow for the`user` it is better to provide the `taxid` since in the `species name` might be typo and this is why in that case the `taxid` will be used to re-create the `species name` and report it back.

**Comment by Nikoleta-v3** [comment]
> Hi, regarding this:
> 
> ```
>     # lines 61 (onwards) and 66 (onwards) were the same, because if both arguments
>     # are given we are still returning results based on the `taxid`.
> ```
> 
> That is true, anyhow for the`user` it is better to provide the `taxid` since in the `species name` might be typo and this is why in that case the `taxid` will be used to re-create the `species name` and report it back.

I get that! But from the implementation one `if` statement is enough. 


> Yes, but one can use e.g.:
> 
> ```
> from orthomap import qlin
> qlin.get_qlin()
> ```
> 
> The `qlin` function is just to be able to use sub-commands and is defining the "sub-module", this is why `orthomap.orthomap` is fine for me, since this is what the sub-command is supposed to do.

Perfect, then it's fine for me too!

**Comment by Nikoleta-v3** [comment]
> Hi, regarding this:
> 
> ```
>     # lines 61 (onwards) and 66 (onwards) were the same, because if both arguments
>     # are given we are still returning results based on the `taxid`.
> ```
> 
> That is true, anyhow for the`user` it is better to provide the `taxid` since in the `species name` might be typo and this is why in that case the `taxid` will be used to re-create the `species name` and report it back.

Good point, I agree let's make sure that the result depends on the `taxid`. Re implementation, having one if statement instead of two is enough. Are you okay with this?

**Comment by kullrich** [comment]
I will now start working on the `orthomap2tei` function to integrate linking the data with `scanpy`. I would just have one question, where we should put a example jupyter notebook file `orthomap-example.ipynb`? Into an `example` folder? All pre-calculated data like the OrthoFinder data for real usage is too big and the link to the zenodo data might be enough. Anyhow, I will extract a minimal example for `orthomap` so that this can be invoked directly.

**Comment by Nikoleta-v3** [comment]
Yeah let's create an `example` folder 👍🏻  I think we will need a very small subset of the OrthoFinder data to write some tests and for examples too 🤔 so we can include them in the `example` folder as well
